#ifndef DLLS_OBJECTS_326_CLOUDSHIPCO_H_
#define DLLS_OBJECTS_326_CLOUDSHIPCO_H_

#include "global.h"

#define CLOUD_SHIP_CONTROL_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gCloudShipControlNullResourceDescriptor[CLOUD_SHIP_CONTROL_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_326_CLOUDSHIPCO_H_ */
