#ifndef DLLS_OBJECTS_333_LASERBEAM_H_
#define DLLS_OBJECTS_333_LASERBEAM_H_

#include "global.h"

#define LASERBEAM_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gLaserBeamNullResourceDescriptor[LASERBEAM_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_333_LASERBEAM_H_ */
