#ifndef DLLS_OBJECTS_337_CFSCALESGAL_H_
#define DLLS_OBJECTS_337_CFSCALESGAL_H_

#include "global.h"

#define CFSCALESGAL_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gCFScalesGalNullResourceDescriptor[CFSCALESGAL_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_337_CFSCALESGAL_H_ */
