#ifndef DLLS_OBJECTS_338_CF_OBJCREAT_H_
#define DLLS_OBJECTS_338_CF_OBJCREAT_H_

#include "global.h"

#define CFOBJCREAT_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gCFObjCreatNullResourceDescriptor[CFOBJCREAT_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_338_CF_OBJCREAT_H_ */
