#ifndef DLLS_OBJECTS_348_CFFORCEFIEL_H_
#define DLLS_OBJECTS_348_CFFORCEFIEL_H_

#include "global.h"

#define CFFORCEFIELD15C_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gCFForceField15CNullResourceDescriptor[CFFORCEFIELD15C_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_348_CFFORCEFIEL_H_ */
