#ifndef DLLS_OBJECTS_353_CFTREASROBO_H_
#define DLLS_OBJECTS_353_CFTREASROBO_H_

#include "global.h"

#define CFTREASROBO_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gCFTreasRoboNullResourceDescriptor[CFTREASROBO_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_353_CFTREASROBO_H_ */
