#ifndef DLLS_OBJECTS_357_CFREMOVALSH_H_
#define DLLS_OBJECTS_357_CFREMOVALSH_H_

#include "global.h"

#define CFREMOVALSH_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gCFRemovalShNullResourceDescriptor[CFREMOVALSH_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_357_CFREMOVALSH_H_ */
