#ifndef DLLS_OBJECTS_360_HOLOPOINT_H_
#define DLLS_OBJECTS_360_HOLOPOINT_H_

#include "global.h"

#define HOLOPOINT_NULL_DESCRIPTOR_WORD_COUNT 2

extern u32 gHoloPointNullResourceDescriptor[HOLOPOINT_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_360_HOLOPOINT_H_ */
