#ifndef DLLS_OBJECTS_374_DFSH_DOOR1S_H_
#define DLLS_OBJECTS_374_DFSH_DOOR1S_H_

#include "global.h"

#define DFSH_DOOR1S_NULL_DESCRIPTOR_WORD_COUNT 12

extern u32 gDFSH_Door1SNullResourceDescriptor[DFSH_DOOR1S_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_374_DFSH_DOOR1S_H_ */
