#ifndef DLLS_OBJECTS_380_GCROBOTPATR_H_
#define DLLS_OBJECTS_380_GCROBOTPATR_H_

#include "global.h"

#define GC_ROBOT_PATR_NULL_DESCRIPTOR_WORD_COUNT 12

extern u32 gGCRobotPatrNullResourceDescriptor[GC_ROBOT_PATR_NULL_DESCRIPTOR_WORD_COUNT];

#endif /* DLLS_OBJECTS_380_GCROBOTPATR_H_ */
