#!/usr/bin/env python3
"""Rank the sub-100 frontier by SAVED-REGISTER BAND WIDTH.

Why this exists: the register-band assignment model is near-exact for narrow
bands and collapses as the band fills.  Measured over 6,288 SFA retail
functions (materialized-ascending + computed-descending, jointly):

    saved regs in band :   2      3      4      5     6+
    GPR                : 99.8%  98.1%  86.0%  48.1%  27.0%
    FP                 : 86.5%  63.8%  55.9%  37.5%  25.6%

So in a <=3-register function the band is effectively deterministic and
STRUCTURE is the only free variable -- a structural fix lands cleanly instead
of being swamped by allocation noise.  At >=6 there is no total order to steer
and declaration-order sweeps are provably flat (four exhaustive sweeps of
720/225/144/121 candidates all returned zero movement, every one a wide-band
function).

This screens every function that differs from retail and ranks the narrow-band
ones by how many bytes they are missing -- i.e. the set where a probe result
will transfer and a fix will stick.

    python3 tools/bandscreen.py                  # narrow-band worklist
    python3 tools/bandscreen.py --max-band 2     # only the 99.8% regime
    python3 tools/bandscreen.py --all            # every differing function
"""
from __future__ import annotations
import argparse, json, os, re, subprocess, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OBJDUMP = REPO / "build" / "binutils" / "powerpc-eabi-objdump"
INS = re.compile(r'^\s*([0-9a-f]+):\t(?:[0-9a-f]{2} ){4}\t(.*)$', re.M)
FUNC = re.compile(r'^([0-9a-f]{8}) <([^>]+)>:\n(.*?)(?=^\S|\Z)', re.S | re.M)
GDST = re.compile(r'^[a-z][a-z0-9_.]*\s+r(\d+),')
FDST = re.compile(r'^(?:lfs|lfd|fmr|psq_l|f[a-z]+)\s+f(\d+),')


def dis(path: Path) -> str | None:
    if not path.is_file():
        return None
    return subprocess.run([str(OBJDUMP), "-M", "gekko", "-drz", str(path)],
                          capture_output=True, text=True).stdout


def parse(text: str) -> dict:
    out = {}
    for m in FUNC.finditer(text):
        out[m.group(2)] = [t.strip() for _, t in INS.findall(m.group(3))]
    return out


def band_widths(ins: list[str]) -> tuple[int, int]:
    g, f = set(), set()
    for t in ins:
        a = GDST.match(t)
        if a and 14 <= int(a.group(1)) <= 31:
            g.add(int(a.group(1)))
        b = FDST.match(t)
        if b and 14 <= int(b.group(1)) <= 31:
            f.add(int(b.group(1)))
    return len(g), len(f)


def differing(t: list[str], c: list[str]) -> tuple[int, str]:
    """(differing instructions, kind).

    kind is STRUCT when the mnemonic stream itself differs -- a real shape
    difference a source edit can address -- and REG when the mnemonics match
    one-for-one and only operands (register numbers) differ, which is
    allocation noise.  Absolute addresses inside operands are noise either way.
    """
    strip = lambda s: re.sub(r'\b[0-9a-f]{4,8} <[^>]+>', '<T>', s)
    T, C = [strip(x) for x in t], [strip(x) for x in c]
    mnem = lambda L: [x.split()[0] for x in L]
    if len(T) == len(C):
        d = sum(1 for a, b in zip(T, C) if a != b)
        kind = "REG" if mnem(T) == mnem(C) else "STRUCT"
        return d, kind
    import difflib
    sm = difflib.SequenceMatcher(None, T, C, autojunk=False)
    d = sum(max(i2 - i1, j2 - j1) for tag, i1, i2, j1, j2
            in sm.get_opcodes() if tag != 'equal')
    return d, "STRUCT"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-v", "--version", default="GSAE01")
    ap.add_argument("--max-band", type=int, default=3,
                    help="max saved regs in EACH band (default 3)")
    ap.add_argument("--all", action="store_true", help="ignore the band filter")
    ap.add_argument("--struct-only", action="store_true",
                    help="only functions whose mnemonic stream differs")
    ap.add_argument("--limit", type=int, default=60)
    args = ap.parse_args()

    cfg = json.loads((REPO / "build" / args.version / "config.json").read_text())
    rows = []
    for u in cfg["units"]:
        if u.get("autogenerated") or not u.get("code_size"):
            continue
        tgt = REPO / u["object"]
        src = REPO / u["object"].replace(f"build/{args.version}/obj/",
                                         f"build/{args.version}/src/")
        tt, cc = dis(tgt), dis(src)
        if not tt or not cc:
            continue
        T, C = parse(tt), parse(cc)
        for fn, ti in T.items():
            ci = C.get(fn)
            if ci is None or not ti:
                continue
            d, kind = differing(ti, ci)
            if d == 0:
                continue
            g, f = band_widths(ti)
            rows.append((d * 4, len(ti) * 4, g, f, kind, u["name"], fn))

    narrow = [r for r in rows if args.all or (r[2] <= args.max_band and r[3] <= args.max_band)]
    if args.struct_only:
        narrow = [r for r in narrow if r[4] == "STRUCT"]
    narrow.sort(key=lambda r: -r[0])
    tag = "all" if args.all else f"<={args.max_band} saved regs in BOTH bands"
    print(f"# frontier ranked by band width -- {tag}")
    print(f"# {len(narrow)} of {len(rows)} differing functions qualify; "
          f"{sum(r[0] for r in narrow)} of {sum(r[0] for r in rows)} diff-bytes\n")
    ns = sum(r[0] for r in narrow if r[4] == "STRUCT")
    print("# of those, %d diff-bytes are STRUCT (mnemonic stream differs -- "
          "source-addressable); the rest are REG (allocation noise)\n" % ns)
    print("%-8s %-8s %-4s %-4s %-7s %-34s %s"
          % ("diffB", "sizeB", "G", "F", "kind", "unit", "function"))
    for r in narrow[:args.limit]:
        print("%-8d %-8d %-4d %-4d %-7s %-34s %s" % r)
    return 0


if __name__ == "__main__":
    sys.exit(main())
