#!/usr/bin/env python3
"""Find pool crutches that are really FORWARD-SUBSTITUTION rows in disguise.

`engine/68` is the specimen.  `docs/priced_classes.md` section 8 priced it at
128 B: retail's `120.0f` is a plain literal minted at `.sdata2+0x44`, but every
in-TU way of spelling the constant either lands the object at the wrong slot or
lets `-opt propagation` sink the single-use temp that reads it, costing the
function 100.0 -> 94.512.  The tree therefore carried a banned 1-element pin.

Section 8 had already named the mechanism and still concluded the row was
priced, because every probe it ran varied HOW THE CONSTANT IS SPELLED.  A76's
engine/5 lever varies the other operand: the sink needs a single-def/single-use
temp, so delete the temp and the constant can be a plain literal.  That took
engine/68 to a byte-identical pool at `matched_code` +0 and the function still
at 100.0.

So a pin is worth re-opening exactly when it is NOT buying pool position:

    pin present  AND  the unit's .sdata2 is still NOT byte-identical
        => the pin is not paying for itself; its only job is to be opaque,
           and that job is what the A76 cure removes.

    pin present  AND  .sdata2 byte-identical
        => load-bearing for the mint order; leave it (adjudicated per §8).

  python3 tools/crutch_sink_scan.py
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
VER = "GSAE01"
OBJDUMP = REPO / "build" / "binutils" / "powerpc-eabi-objdump"
if not OBJDUMP.is_file():
    OBJDUMP = REPO / "build" / "binutils" / "powerpc-eabi-objdump.exe"

PIN_RE = re.compile(
    r"^\s*(?:static\s+)?const\s+[A-Za-z_][A-Za-z_0-9]*\s+"
    r"([A-Za-z_][A-Za-z_0-9]*)\s*\[\s*1\s*\]\s*=")
LBL_RE = re.compile(
    r"^\s*(?:static\s+)?const\s+[A-Za-z_][A-Za-z_0-9]*\s+(lbl_[0-9A-Fa-f]+)\s*=")


def section(obj, name):
    out = subprocess.run([str(OBJDUMP), "-s", "-j", name, str(obj)],
                         capture_output=True, text=True).stdout
    b = bytearray()
    for ln in out.splitlines()[2:]:          # objdump -s prints its own path
        p = ln.split()
        if len(p) < 2 or not all(c in "0123456789abcdef" for c in p[0]):
            continue
        for w in p[1:]:
            if len(w) == 8 and all(c in "0123456789abcdef" for c in w):
                b += bytes.fromhex(w)
    return bytes(b)


def main():
    cfg = json.loads((REPO / "build" / VER / "config.json").read_text())
    by_src = {}
    for u in cfg["units"]:
        if u.get("autogenerated"):
            continue
        by_src["src/" + u["name"]] = u

    rows = []
    for src, u in sorted(by_src.items()):
        p = REPO / src
        if not p.is_file():
            continue
        pins = []
        for i, line in enumerate(p.read_text(encoding="utf-8",
                                             errors="replace").split("\n"), 1):
            m = PIN_RE.match(line) or LBL_RE.match(line)
            if m:
                pins.append((i, m.group(1)))
        if not pins:
            continue
        tgt = REPO / u["object"]
        our = REPO / u["object"].replace("/obj/", "/src/", 1)
        if not tgt.is_file() or not our.is_file():
            continue
        t, c = section(tgt, ".sdata2"), section(our, ".sdata2")
        ident = (t == c and len(t) > 0)
        rows.append((src, pins, ident, len(t), len(c)))

    print("%-52s %-9s %-6s %s" % ("UNIT", "sdata2", "PINS", "VERDICT"))
    reopen = 0
    for src, pins, ident, lt, lc in sorted(rows, key=lambda r: (r[2], r[0])):
        if ident:
            v = "load-bearing (pool already byte-identical) -- leave"
        else:
            v = "RE-OPEN: pin is not buying pool position"
            reopen += 1
        print("%-52s %-9s %-6d %s"
              % (src.replace("src/", "")[:52],
                 "SAME" if ident else "%d/%d" % (lc, lt), len(pins), v))
        if not ident:
            for ln, name in pins:
                print("      %s:%d  %s" % (src, ln, name))
    print("\n%d units carry a pin; %d have a pool the pin is NOT fixing"
          % (len(rows), reopen))


if __name__ == "__main__":
    sys.exit(main())
