#!/usr/bin/env python3
"""DATA-section relocation-TARGET check: catch a table that points at the wrong
thing.

The documented blind spot of fuzzy_match_percent is that objdiff normalises
relocation TARGETS, so a right displacement in front of a wrong constant reads
as a perfect match. sda_reloc_check and reloc_target_audit close that hole for
`.text`. Nothing closed it for DATA, where the same normalisation applies and
the payload is worse: the relocated words in `.data`/`.rodata`/`.sdata` are
FUNCTION and OBJECT POINTERS -- ObjectDescriptor hooks, state tables, vtables,
string tables. A descriptor wired to the neighbouring function is a live game
defect that every current gate passes:

  * objdiff normalises the relocated words away, so a table that is entirely
    pointers is compared against nothing at all.
  * objdiff also pairs data by SYMBOL NAME, and across the incomplete units the
    names barely overlap -- 1533 paired against 2253 ours-only and 2470
    retail-only, because retail's carved objects carry autogenerated
    `lbl_ADDR`/`data_ADDR` names where our source has real ones. Most data is
    therefore not compared by name either.
  * The main.dol sha1 is blind while the unit is INCOMPLETE, because the link
    consumes the retail object. The defect appears the instant it is promoted.

Because name pairing is what fails, this does not use it. It compares whole
SECTIONS positionally, which needs no symbol correspondence at all: for each
data section the two objects agree the size of, every 4-byte word is resolved
and the two word images are compared.

A word is resolved to the ADDRESS its relocation names when it carries one, and
to its literal bytes when it does not. That single rule is what makes the
comparison possible, because the two sides spell the same pointer differently:
our pre-link object holds an ADDR32 relocation and zeros in the data, while
retail's carved object often holds the resolved address as a literal word.
Comparing raw bytes calls every such pair a mismatch; comparing resolved images
calls them equal. Pointer identity is therefore by ADDRESS, never by name -- the
same target is routinely spelled two ways, our `FUN_80259288` against retail's
`GXSetCullMode`, and a name comparison reports every un-renamed Ghidra alias as
a wrong pointer.

Verdicts are graded, because a section that merely EMITS IN A DIFFERENT ORDER is
a known TU-boundary artifact and not a value defect:

  PERM       same multiset of words, different order  -- emission-order artifact
  PTR-DIFF   a relocated word points somewhere else   -- the real class
  VAL-DIFF   a literal word holds a different value

Filters. Each census below is measured on the tree this was written against,
and the matching --no-* flag re-derives it:

  * SKIP complete=True UNITS. The sha1 proves them byte-identical, so a finding
    there is false by construction. 0 phantoms here -- the whole 851-unit,
    8777-pointer-word population is clean -- but the mechanism that produces
    them is real: retail sometimes encodes a reference with no relocation at
    all, and a guard counting relocations that exist and fail cannot see one
    that is absent.
  * SIZE MISMATCH. Sections of different size are not positionally comparable,
    and the difference is already visible to section_size_check. 50 sections.
  * ASYMMETRIC DECLINE. If the two sides fail to resolve a DIFFERENT NUMBER of
    words the images have desynchronised and every word past that point is
    mis-paired. Skip the section. 0 phantoms; 1 section skipped.
  * INTERIOR TARGETS. A pointer word whose target on either side is NOT the
    address of a named symbol points into the middle of a function -- a SWITCH
    JUMP TABLE. Those shift wholesale whenever our codegen for the function
    differs by a single instruction, which is a match defect the fuzzy score
    already reports and never a wrong-pointer defect. 2 phantoms, and they are
    the ONLY two findings the tool produces without this filter, both of exactly
    that shape: player's `.data` differing in 51 consecutive words by a uniform
    +4, and engine/2's differing in 27 words that are retail's own list rotated
    by one entry. Neither differing address is named anywhere in symbols.txt. A
    real function pointer always names a function ENTRY, which symbols.txt has.
  * BSS. No content.

Ground truth is orig/GSAE01/sys/main.dol plus the retail objects; report.json is
read only for the `complete` flag and the printed score.

usage: python3 tools/data_reloc_check.py [unit-substring ...]
                 [--no-complete-filter] [--no-asym-guard] [--perm] [--vals] [-v]
       --perm  report PERM sections too (emission order, not a value defect)
       --vals  report VAL-DIFF on literal words too (mostly pool reordering)
exit status: 1 if any PTR-DIFF finding, else 0.
"""
import json
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from scope_guard import require_nonempty
import sda_reloc_check as S
from sda_reloc_check import ROOT, LBL_RE, Obj, load_retail_addrs

R_ADDR32 = 1
FN_ADDR_RE = re.compile(r"^(?:FUN|fun|fn)_([0-9A-Fa-f]{8})$")
DATA_SECS = (".data", ".rodata", ".sdata", ".sdata2", ".data1", ".rodata1",
             ".ctors", ".dtors", ".init")


def all_addrs():
    """Every address symbols.txt names, ambiguities included.

    load_retail_addrs() drops names that map to several addresses, which is
    right for name->address lookup and wrong here: the question is only whether
    an address is named at all.
    """
    out = set()
    path = os.path.join(ROOT, "config/GSAE01/symbols.txt")
    for line in open(path):
        g = re.match(r"^(\S+) = \.(\w+):0x([0-9A-Fa-f]{8});", line)
        if g:
            out.add(int(g.group(3), 16))
    return out


def sym_addr(name, RA):
    a = RA.get(name)
    if a is not None:
        return a
    g = FN_ADDR_RE.match(name) or LBL_RE.match(name)
    return int(g.group(1), 16) if g else None


def resolved_section(o, shndx, RA):
    """([(word, kind)], n_declined) for a whole data section.

    kind 'p': the word carries an ADDR32 relocation, resolved to an address.
    kind 'b': a literal datum.
    An unresolvable pointer word is dropped and counted so the caller can
    require the two sides to have declined equally.
    """
    data = o.e.sec_data(shndx)
    rel = {}
    for off, typ, si, add in o.e.relocs(shndx):
        if typ == R_ADDR32:
            rel[off] = (o.syms[si][0], add)
    out, declined = [], 0
    for i in range(0, len(data) - len(data) % 4, 4):
        if i in rel:
            nm, add = rel[i]
            a = sym_addr(nm, RA)
            if a is None:
                declined += 1
                continue
            out.append((a + add, "p"))
        else:
            out.append((struct.unpack(">I", data[i:i + 4])[0], "b"))
    return out, declined


def sections(o):
    """[(name, occurrence, index)] for comparable data sections, in file order."""
    out, seen = [], {}
    for i, s in enumerate(o.e.sh):
        if s["type"] == S.SHT_NOBITS or s["name"] not in DATA_SECS or not s["size"]:
            continue
        k = seen.get(s["name"], 0)
        seen[s["name"]] = k + 1
        out.append((s["name"], k, i))
    return out


def main():
    no_complete = "--no-complete-filter" in sys.argv
    no_asym = "--no-asym-guard" in sys.argv
    want_perm = "--perm" in sys.argv
    want_vals = "--vals" in sys.argv
    no_interior = "--no-interior-guard" in sys.argv
    verbose = "-v" in sys.argv
    pats = [a for a in sys.argv[1:] if not a.startswith("-")]

    RA = load_retail_addrs()
    NAMED = all_addrs()
    rep = json.load(open(os.path.join(ROOT, "build/GSAE01/report.json")))
    complete = {u["name"]: u["metadata"].get("complete") for u in rep["units"]}
    pct = {u["name"]: u["measures"].get("fuzzy_match_percent", 0) for u in rep["units"]}
    units = [u for u in json.load(open(os.path.join(ROOT, "objdiff.json")))["units"]
             if "base_path" in u and "target_path" in u]
    require_nonempty(pats, [u["name"] for u in units])

    findings = []
    n_units = n_secs = n_words = n_ptr = n_asym = n_size = n_perm = n_interior = 0
    for u in units:
        name = u["name"]
        if pats and not any(p in name for p in pats):
            continue
        if complete.get(name) and not no_complete:
            continue
        po = os.path.join(ROOT, u["base_path"])
        pr = os.path.join(ROOT, u["target_path"])
        if not (os.path.exists(po) and os.path.exists(pr)):
            continue
        try:
            O, T = Obj(po), Obj(pr)
        except Exception as ex:
            sys.stderr.write("[skip %s: %s]\n" % (name, ex))
            continue
        so = {(n, k): i for n, k, i in sections(O)}
        st = {(n, k): i for n, k, i in sections(T)}
        common = [k for k in so if k in st]
        if not common:
            continue
        n_units += 1
        for key in sorted(common):
            io_, do = resolved_section(O, so[key], RA)
            it_, dt = resolved_section(T, st[key], RA)
            if O.e.sh[so[key]]["size"] != T.e.sh[st[key]]["size"]:
                n_size += 1
                continue
            if do != dt and not no_asym:
                n_asym += 1
                continue
            if len(io_) != len(it_):
                n_asym += 1
                continue
            n_secs += 1
            n_words += len(io_)
            n_ptr += sum(1 for w, k in io_ if k == "p")
            if io_ == it_:
                continue
            if sorted(io_) == sorted(it_):
                n_perm += 1
                if want_perm:
                    findings.append(dict(unit=name, pct=pct.get(name, 0),
                                         sec="%s#%d" % key, kind="PERM", words=[]))
                continue
            bad = []
            for i, ((wo, ko), (wt, kt)) in enumerate(zip(io_, it_)):
                if wo == wt:
                    continue
                if ko == "b" and kt == "b" and not want_vals:
                    continue
                if (ko == "p" or kt == "p") and not no_interior and \
                        (wo not in NAMED or wt not in NAMED):
                    n_interior += 1
                    continue
                bad.append((i * 4, wo, ko, wt, kt))
            if bad:
                findings.append(dict(unit=name, pct=pct.get(name, 0),
                                     sec="%s#%d" % key,
                                     kind="PTR-DIFF" if any(k == "p" or j == "p"
                                                            for _, _, k, _, j in bad)
                                          else "VAL-DIFF",
                                     words=bad))

    hard = 0
    for f in findings:
        if f["kind"] == "PTR-DIFF":
            hard += 1
        print("*** [%s] %s  %s  (%.2f%%)  %d word(s)"
              % (f["kind"], f["unit"], f["sec"], f["pct"], len(f["words"])))
        for off, wo, ko, wt, kt in (f["words"] if verbose else f["words"][:8]):
            print("      +0x%04x  ours %s 0x%08x   retail %s 0x%08x"
                  % (off, ko, wo, kt, wt))
        if not verbose and len(f["words"]) > 8:
            print("      ... %d more" % (len(f["words"]) - 8))
    print("[incomplete units with data: %d] [sections compared: %d] "
          "[words compared: %d, of which %d relocated pointers] "
          "[skipped: %d size-mismatch, %d asymmetric-decline, "
          "%d interior/jump-table words] "
          "[PERM sections: %d] [findings: %d]"
          % (n_units, n_secs, n_words, n_ptr, n_size, n_asym, n_interior,
             n_perm, len(findings)))
    return 1 if hard else 0


sys.exit(main())
