#!/usr/bin/env python3
"""Detect symbol-name divergence between the retail carve and our objects.

WHY THIS EXISTS
---------------
objdiff pairs a function in our object with its retail counterpart **by symbol
name**.  If the two names disagree, the pair is lost: our function scores as
unmatched and the retail one as missing, and the unit's fuzzy collapses in
proportion to that function's size -- with a completely green
`locked_ninja.sh` (EXIT=0, 0 FAILED), because nothing about the *link* is
wrong.  A five-function rename once took `gametext_tail` from 99.07 to 55.47
this way.

`config/GSAE01/symbols.txt` is BUILD INPUT: `configure.py` lists it in
`config.split_deps`, so editing it re-runs the splitter and re-carves the
retail objects under `build/GSAE01/obj/`.  A rename applied to BOTH
`symbols.txt` and the C source therefore stays paired.  A rename applied to
only one of them -- or applied to symbols.txt but missed in one of several
units that define/declare the name -- silently unpairs.

This checks the invariant directly, cheaply, and without rebuilding anything.

    python3 tools/pairing_check.py            # whole project
    python3 tools/pairing_check.py textrender # units matching a substring

Exit status is 1 if any unit has a divergence, so it can gate a commit.
"""
from __future__ import annotations
import json, subprocess, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OBJDUMP = REPO / "build" / "binutils" / "powerpc-eabi-objdump"


def func_syms(obj: Path) -> set[str] | None:
    if not obj.is_file():
        return None
    out = subprocess.run([str(OBJDUMP), "-t", str(obj)],
                         capture_output=True, text=True).stdout
    syms = set()
    for line in out.splitlines():
        # "<addr> <flags> F <section> <size> <name>"
        parts = line.split()
        if len(parts) >= 6 and "F" in parts[1:3] and ".text" in line:
            syms.add(parts[-1])
    return syms


def refs(symbol: str, version: str = "GSAE01") -> int:
    """Blast radius: every unit whose retail object references `symbol`.

    A rename must be verified on ALL of these, not just the defining unit --
    objdiff compares relocation target names, so a name mismatch shows up as a
    diff at every call site in every calling unit.
    """
    cfg = json.loads((REPO / "build" / version / "config.json").read_text())
    hits = []
    for u in cfg["units"]:
        if u.get("autogenerated") or not u.get("code_size"):
            continue
        obj = REPO / u["object"]
        if not obj.is_file():
            continue
        out = subprocess.run([str(OBJDUMP), "-r", str(obj)],
                             capture_output=True, text=True).stdout
        n = sum(1 for line in out.splitlines()
                if line.split()[-1:] == [symbol])
        if n:
            hits.append((n, u["name"]))
    hits.sort(reverse=True)
    print(f"'{symbol}' is referenced by {len(hits)} unit(s):")
    for n, name in hits:
        print(f"   {n:4d} reloc(s)  {name}")
    print("\nVerify `tools/unitfuzzy.py` on EVERY unit above after a rename, "
          "not just the defining one.")
    return 0


def main() -> int:
    version = "GSAE01"
    if len(sys.argv) > 2 and sys.argv[1] == "--refs":
        return refs(sys.argv[2], version)
    filt = sys.argv[1] if len(sys.argv) > 1 else ""
    cfg = json.loads((REPO / "build" / version / "config.json").read_text())
    bad = checked = benign = 0
    for u in cfg["units"]:
        if u.get("autogenerated") or not u.get("code_size"):
            continue
        name = u["name"]
        if filt and filt not in name:
            continue
        tgt = REPO / u["object"]
        src = REPO / u["object"].replace(f"build/{version}/obj/",
                                         f"build/{version}/src/")
        T, C = func_syms(tgt), func_syms(src)
        if T is None or C is None:
            continue
        checked += 1
        only_t, only_c = sorted(T - C), sorted(C - T)
        if only_t:
            # DANGEROUS: a retail function with no counterpart of ours cannot be
            # paired, so its bytes score zero.  This is the rename-failure shape.
            bad += 1
            print(f"\n!! {name}")
            for s in only_t:
                print(f"     RETAIL ONLY (unpaired, scores 0) : {s}")
            for s in only_c:
                print(f"     ours only  (not scored)          : {s}")
        elif only_c:
            benign += 1
    print(f"\n{checked} units checked.")
    print(f"  {bad} with RETAIL-ONLY symbols  <-- lost pairing, real score loss")
    print(f"  {benign} with only ours-only symbols (statics/never-inlined "
          f"helpers; objdiff does not score them -- benign)")
    if bad:
        print("\nA unit listed above scores ZERO on each retail-only function "
              "while `locked_ninja.sh` stays green.\n"
              "Fix: make config/GSAE01/symbols.txt and the C source agree on "
              "the name, rebuild, re-run.")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
