#!/usr/bin/env python3
"""Project coherent translation units between retail DOL versions.

The active EN v1.0 configuration remains the source of translation-unit names.
Code, initialized data, exception metadata, and BSS boundaries are inferred from
unique normalized binary anchors and stable address-delta corridors. A source
unit is claimed only when every owned section maps legally in the target;
uncertain ranges stay autogenerated and remain in the progress denominator.
"""

from __future__ import annotations

import argparse
import bisect
import hashlib
import json
import re
import struct
from collections import defaultdict
from dataclasses import dataclass, replace
from pathlib import Path

from orig.dol_xrefs import DolFile, FunctionSymbol, load_function_symbols


CODE_SECTIONS = {"init", "text"}
SECTION_INDEX = {
    "init": 0,
    "text": 1,
    "extab": 7,
    "extabindex": 8,
    "ctors": 9,
    "dtors": 10,
    "rodata": 11,
    "data": 12,
    "sdata": 13,
    "sdata2": 14,
}
TOP16_MASK_OPCODES = {
    7,
    8,
    10,
    11,
    12,
    13,
    14,
    15,
    24,
    25,
    26,
    27,
    28,
    29,
    *range(32, 56),
}
TOP16_LOW2_MASK_OPCODES = {56, 57, 60, 61}
SPLIT_RANGE_RE = re.compile(
    r"^\s*(\.?\S+)\s+start:0x([0-9A-Fa-f]+)\s+end:0x([0-9A-Fa-f]+)"
)


@dataclass(frozen=True)
class SplitRange:
    unit: str
    section: str
    start: int
    end: int


@dataclass(frozen=True)
class PortedRange:
    source: SplitRange
    target_start: int
    target_end: int
    source_functions: tuple[FunctionSymbol, ...]
    target_functions: tuple[FunctionSymbol, ...]


@dataclass(frozen=True)
class SymbolSpan:
    name: str
    section: str
    start: int
    end: int

    @property
    def size(self) -> int:
        return self.end - self.start


def mask_instruction(word: int) -> int:
    opcode = word >> 26
    if opcode == 18:
        return word & 0xFC000003
    if opcode == 16:
        return word & 0xFFFF0003
    if opcode in TOP16_MASK_OPCODES:
        return word & 0xFFFF0000
    if opcode in TOP16_LOW2_MASK_OPCODES:
        return word & 0xFFFF0003
    return word


def read_dol_range(dol: DolFile, start: int, size: int) -> bytes:
    for section in dol.sections:
        if section.address <= start and start + size <= section.address + section.size:
            offset = section.offset + start - section.address
            return dol.data[offset : offset + size]
    raise ValueError(f"Range 0x{start:08X}-0x{start + size:08X} is outside {dol.path}")


def function_signature(dol: DolFile, function: FunctionSymbol) -> bytes:
    raw = read_dol_range(dol, function.address, function.size)
    if len(raw) % 4:
        raise ValueError(
            f"Function {function.name} has non-word size 0x{function.size:X}"
        )
    digest = hashlib.sha1()
    for (word,) in struct.iter_unpack(">I", raw):
        digest.update(struct.pack(">I", mask_instruction(word)))
    return digest.digest()


def load_splits(path: Path) -> tuple[list[str], list[SplitRange]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    header_end = len(lines)
    ranges: list[SplitRange] = []
    unit: str | None = None
    for index, line in enumerate(lines):
        if line and not line[0].isspace() and ":" in line:
            unit_name, _, _ = line.partition(":")
            if unit_name == "Sections":
                continue
            if header_end == len(lines):
                header_end = index
            unit = unit_name
            continue
        if unit is None:
            continue
        match = SPLIT_RANGE_RE.match(line)
        if match is None:
            continue
        section = match.group(1).removeprefix(".")
        ranges.append(
            SplitRange(
                unit=unit.replace("\\", "/"),
                section=section,
                start=int(match.group(2), 16),
                end=int(match.group(3), 16),
            )
        )
    while header_end > 0 and not lines[header_end - 1].strip():
        header_end -= 1
    return lines[:header_end], ranges


def functions_in_range(
    functions_by_section: dict[str, list[FunctionSymbol]], split: SplitRange
) -> tuple[FunctionSymbol, ...]:
    return tuple(
        function
        for function in functions_by_section.get(split.section, [])
        if split.start <= function.address
        and function.address + function.size <= split.end
    )


def unique_function_matches(
    source_dol: DolFile,
    source_functions: list[FunctionSymbol],
    target_dol: DolFile,
    target_functions: list[FunctionSymbol],
) -> dict[int, FunctionSymbol]:
    source_by_signature: dict[tuple[str, bytes], list[FunctionSymbol]] = defaultdict(
        list
    )
    target_by_signature: dict[tuple[str, bytes], list[FunctionSymbol]] = defaultdict(
        list
    )
    source_by_name: dict[str, list[FunctionSymbol]] = defaultdict(list)
    target_by_name: dict[str, list[FunctionSymbol]] = defaultdict(list)
    for function in source_functions:
        if function.section in CODE_SECTIONS:
            source_by_name[function.name].append(function)
            source_by_signature[
                (function.section, function_signature(source_dol, function))
            ].append(function)
    for function in target_functions:
        if function.section in CODE_SECTIONS:
            target_by_name[function.name].append(function)
            target_by_signature[
                (function.section, function_signature(target_dol, function))
            ].append(function)

    matches: dict[int, FunctionSymbol] = {}
    for signature, candidates in source_by_signature.items():
        targets = target_by_signature.get(signature, [])
        if len(candidates) == 1 and len(targets) == 1:
            matches[candidates[0].address] = targets[0]
    used_targets = {function.address for function in matches.values()}
    for name, candidates in source_by_name.items():
        targets = target_by_name.get(name, [])
        if len(candidates) != 1 or len(targets) != 1:
            continue
        source_function = candidates[0]
        target_function = targets[0]
        if (
            source_function.address in matches
            or target_function.address in used_targets
            or source_function.section != target_function.section
            or function_signature(source_dol, source_function)
            != function_signature(target_dol, target_function)
        ):
            continue
        matches[source_function.address] = target_function
        used_targets.add(target_function.address)
    return matches


def dol_section(dol: DolFile, section: str):
    index = SECTION_INDEX[section]
    return next(item for item in dol.sections if item.index == index)


def normalized_section_words(dol: DolFile, section: str) -> tuple[object, list[int]]:
    dol_range = dol_section(dol, section)
    raw = dol.data[dol_range.offset : dol_range.offset + dol_range.size]
    words: list[int] = []
    for offset in range(0, len(raw), 4):
        chunk = raw[offset : offset + 4].ljust(4, b"\0")
        (word,) = struct.unpack(">I", chunk)
        if section in CODE_SECTIONS:
            word = mask_instruction(word)
        elif 0x80000000 <= word < 0x81800000:
            # Relocated pointers move with their targets between versions.  A
            # pointer marker retains the surrounding data shape without
            # pretending the absolute value is stable.
            word = 0xFFFFFFFF
        words.append(word)
    return dol_range, words


def build_boundary_map(
    section: str,
    boundaries: set[int],
    source_dol: DolFile,
    target_dol: DolFile,
    source_functions: list[FunctionSymbol],
    matches: dict[int, FunctionSymbol],
) -> tuple[dict[int, int], dict[int, int]]:
    """Map split boundaries using direct binary anchors and stable corridors."""

    source_range, source_words = normalized_section_words(source_dol, section)
    target_range, target_words = normalized_section_words(target_dol, section)
    direct = {
        source_range.address: target_range.address,
        source_range.address
        + source_range.size: target_range.address
        + target_range.size,
    }

    if section in CODE_SECTIONS:
        source_by_address = {item.address: item for item in source_functions}
        for source_address, target_function in matches.items():
            source_function = source_by_address[source_address]
            if not (
                source_range.address
                <= source_address
                < source_range.address + source_range.size
            ):
                continue
            direct[source_address] = target_function.address
            direct[source_address + source_function.size] = (
                target_function.address + target_function.size
            )
    else:
        # Eight normalized words are long enough to make ordinary data
        # contexts unique while still surviving small localized edits.
        context_words = 8
        target_index: dict[int, int] = {}
        duplicate_hashes: set[int] = set()
        for index in range(len(target_words) - context_words + 1):
            signature = hash(tuple(target_words[index : index + context_words]))
            if signature in target_index:
                duplicate_hashes.add(signature)
            else:
                target_index[signature] = index

        for boundary in boundaries:
            if boundary in direct:
                continue
            source_index = (boundary - source_range.address) // 4
            candidates: list[int] = []
            if 0 <= source_index <= len(source_words) - context_words:
                source_context = source_words[
                    source_index : source_index + context_words
                ]
                signature = hash(tuple(source_context))
                target_index_value = target_index.get(signature)
                if (
                    target_index_value is not None
                    and signature not in duplicate_hashes
                    and source_context
                    == target_words[
                        target_index_value : target_index_value + context_words
                    ]
                ):
                    candidates.append(target_index_value)
            if context_words <= source_index <= len(source_words):
                source_context = source_words[
                    source_index - context_words : source_index
                ]
                signature = hash(tuple(source_context))
                target_index_value = target_index.get(signature)
                if (
                    target_index_value is not None
                    and signature not in duplicate_hashes
                    and source_context
                    == target_words[
                        target_index_value : target_index_value + context_words
                    ]
                ):
                    candidates.append(target_index_value + context_words)
            if candidates and len(set(candidates)) == 1:
                direct[boundary] = target_range.address + candidates[0] * 4

    # Discard the rare repeated-code anchor that would make the global mapping
    # run backwards.  Source and target object order is otherwise preserved.
    monotonic: dict[int, int] = {}
    previous_target = -1
    for source_address, target_address in sorted(direct.items()):
        if target_address > previous_target:
            monotonic[source_address] = target_address
            previous_target = target_address
    direct = monotonic

    inferred = dict(direct)
    direct_addresses = sorted(direct)
    for boundary in sorted(boundaries):
        if boundary in inferred:
            continue
        index = bisect.bisect_left(direct_addresses, boundary)
        if index == 0 or index == len(direct_addresses):
            continue
        before = direct_addresses[index - 1]
        after = direct_addresses[index]
        before_delta = direct[before] - before
        after_delta = direct[after] - after
        if before_delta == after_delta:
            target_boundary = boundary + before_delta
            # Context anchors can sit inside strings or packed byte tables and
            # therefore change phase across versions.  Inferred object
            # boundaries retain their source word phase; otherwise an aligned
            # EN symbol can be projected to a halfword address between two
            # unaligned string anchors.
            target_boundary += (boundary - target_boundary) % 4
            inferred[boundary] = target_boundary

    # Localized strings and tables can change the delta on either side of a
    # boundary.  Interpolate the remaining address within its two direct
    # anchors, then let target-symbol and overlap validation decide whether the
    # resulting TU is safe to claim.
    for boundary in sorted(boundaries):
        if boundary in inferred:
            continue
        index = bisect.bisect_left(direct_addresses, boundary)
        if index == 0 or index == len(direct_addresses):
            continue
        before = direct_addresses[index - 1]
        after = direct_addresses[index]
        source_width = after - before
        target_width = direct[after] - direct[before]
        if source_width <= 0 or target_width <= 0:
            continue
        source_offset = boundary - before
        target_boundary = direct[before] + round(
            source_offset * target_width / source_width
        )
        target_boundary += (boundary - target_boundary) % 4
        if direct[before] < target_boundary < direct[after]:
            inferred[boundary] = target_boundary
    return direct, inferred


def build_all_boundary_maps(
    source_splits: list[SplitRange],
    source_dol: DolFile,
    target_dol: DolFile,
    source_functions: list[FunctionSymbol],
    matches: dict[int, FunctionSymbol],
) -> tuple[dict[str, dict[int, int]], dict[str, tuple[int, int]]]:
    boundaries_by_section: dict[str, set[int]] = defaultdict(set)
    for split in source_splits:
        boundaries_by_section[split.section].update((split.start, split.end))

    result: dict[str, dict[int, int]] = {}
    anchor_counts: dict[str, tuple[int, int]] = {}
    for section in SECTION_INDEX:
        boundaries = boundaries_by_section.get(section)
        if not boundaries:
            continue
        direct, inferred = build_boundary_map(
            section,
            boundaries,
            source_dol,
            target_dol,
            source_functions,
            matches,
        )
        result[section] = inferred
        anchor_counts[section] = (
            sum(boundary in direct for boundary in boundaries),
            sum(boundary in inferred for boundary in boundaries),
        )

    # These zero-filled spans have no bytes to anchor, but their total widths
    # are invariant across the retail versions.  Their positions are pinned by
    # the initialized sections on either side.
    zero_section_origins = {
        "bss": (
            dol_section(source_dol, "data").address
            + dol_section(source_dol, "data").size,
            dol_section(target_dol, "data").address
            + dol_section(target_dol, "data").size,
        ),
        "sbss": (
            dol_section(source_dol, "sdata").address
            + dol_section(source_dol, "sdata").size,
            dol_section(target_dol, "sdata").address
            + dol_section(target_dol, "sdata").size,
        ),
    }
    for section, (source_origin, target_origin) in zero_section_origins.items():
        boundaries = boundaries_by_section.get(section)
        if not boundaries:
            continue
        delta = target_origin - source_origin
        result[section] = {boundary: boundary + delta for boundary in boundaries}
        anchor_counts[section] = (0, len(boundaries))
    return result, anchor_counts


def load_symbol_spans(path: Path) -> dict[str, tuple[SymbolSpan, ...]]:
    spans: dict[str, list[SymbolSpan]] = defaultdict(list)
    size_re = re.compile(r"\bsize:0x([0-9A-Fa-f]+)\b")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = SYMBOL_LINE_RE.match(line)
        size_match = size_re.search(line)
        if match is None or size_match is None:
            continue
        start = int(match.group(3), 16)
        size = int(size_match.group(1), 16)
        if size:
            spans[match.group(2)].append(
                SymbolSpan(match.group(1), match.group(2), start, start + size)
            )
    return {
        section: tuple(sorted(section_spans, key=lambda span: (span.start, span.end)))
        for section, section_spans in spans.items()
    }


def symbol_span_index(
    spans: dict[str, tuple[SymbolSpan, ...]],
    *,
    include_address_symbols: bool = False,
) -> dict[str, tuple[list[int], list[int]]]:
    result: dict[str, tuple[list[int], list[int]]] = {}
    for section, section_spans in spans.items():
        starts: list[int] = []
        prefix_max_end: list[int] = []
        maximum = 0
        for span in section_spans:
            if (
                not include_address_symbols
                and ADDRESS_SYMBOL_RE.match(span.name) is not None
            ):
                continue
            starts.append(span.start)
            maximum = max(maximum, span.end)
            prefix_max_end.append(maximum)
        result[section] = (starts, prefix_max_end)
    return result


def load_symbol_span_index(
    path: Path,
    *,
    include_address_symbols: bool = False,
) -> dict[str, tuple[list[int], list[int]]]:
    return symbol_span_index(
        load_symbol_spans(path),
        include_address_symbols=include_address_symbols,
    )


def boundary_crosses_symbol(
    span_index: dict[str, tuple[list[int], list[int]]],
    section: str,
    boundary: int,
) -> bool:
    starts, prefix_max_end = span_index.get(section, ([], []))
    index = bisect.bisect_left(starts, boundary) - 1
    return index >= 0 and prefix_max_end[index] > boundary


def normalized_span_signature(dol: DolFile, span: SymbolSpan) -> bytes:
    """Return span bytes with relocatable DOL pointers normalized."""

    raw = bytearray(read_dol_range(dol, span.start, span.size))
    for offset in range((-span.start) % 4, len(raw) - 3, 4):
        (word,) = struct.unpack_from(">I", raw, offset)
        if span.section in CODE_SECTIONS:
            struct.pack_into(">I", raw, offset, mask_instruction(word))
        elif 0x80000000 <= word < 0x81800000:
            struct.pack_into(">I", raw, offset, 0xFFFFFFFF)
    return bytes(raw)


def weak_symbol_name(name: str) -> bool:
    return (
        ADDRESS_SYMBOL_RE.match(name) is not None
        or re.match(r"^@\d+$", name) is not None
    )


def snap_symbol_boundaries(
    source_splits: list[SplitRange],
    boundary_maps: dict[str, dict[int, int]],
    source_dol: DolFile,
    target_dol: DolFile,
    source_spans: dict[str, tuple[SymbolSpan, ...]],
    target_spans: dict[str, tuple[SymbolSpan, ...]],
    target_symbol_span_index: dict[str, tuple[list[int], list[int]]],
    target_all_symbol_span_index: dict[str, tuple[list[int], list[int]]],
) -> tuple[dict[str, dict[int, int]], int]:
    """Snap rejected inferred boundaries to proven homologous symbol edges."""

    splits_by_boundary: dict[tuple[str, int], list[SplitRange]] = defaultdict(list)
    for split in source_splits:
        splits_by_boundary[(split.section, split.start)].append(split)
        splits_by_boundary[(split.section, split.end)].append(split)

    proposals: dict[tuple[str, int], int] = {}
    for section, section_map in boundary_maps.items():
        if section in CODE_SECTIONS:
            continue
        section_source_spans = source_spans.get(section, ())
        section_target_spans = target_spans.get(section, ())
        for source_boundary, target_boundary in section_map.items():
            touching = splits_by_boundary.get((section, source_boundary), [])
            currently_rejected = False
            for split in touching:
                target_start = section_map.get(split.start)
                target_end = section_map.get(split.end)
                if target_start is None or target_end is None:
                    continue
                size_drift = split.end - split.start != target_end - target_start
                index = (
                    target_all_symbol_span_index
                    if size_drift
                    else target_symbol_span_index
                )
                if boundary_crosses_symbol(index, section, target_boundary):
                    currently_rejected = True
                    break
            if not currently_rejected:
                continue

            crossing = [
                span
                for span in section_target_spans
                if span.start < target_boundary < span.end
            ]
            if len(crossing) != 1:
                continue
            target_span = crossing[0]
            target_signature = normalized_span_signature(target_dol, target_span)
            named_homolog = any(
                source_span.name == target_span.name
                and (
                    source_span.start == source_boundary
                    or source_span.end == source_boundary
                )
                for source_span in section_source_spans
            )
            weak_zero_extended_tail = any(
                weak_symbol_name(source_span.name)
                and source_span.end == source_boundary
                and 0 < target_span.size - source_span.size <= 8
                and target_signature[: source_span.size]
                == normalized_span_signature(source_dol, source_span)
                and not any(target_signature[source_span.size :])
                for source_span in section_source_spans
            )
            if (
                not weak_symbol_name(target_span.name)
                and not named_homolog
                and not weak_zero_extended_tail
            ):
                continue
            candidates: list[int] = []
            for source_span in section_source_spans:
                source_signature = normalized_span_signature(source_dol, source_span)
                if source_span.end == source_boundary:
                    candidate = target_span.end
                elif source_span.start == source_boundary:
                    candidate = target_span.start
                else:
                    continue
                exact = (
                    source_span.size == target_span.size
                    and source_signature == target_signature
                )
                zero_extended_tail = (
                    candidate == target_span.end
                    and 0 < target_span.size - source_span.size <= 8
                    and target_signature[: source_span.size] == source_signature
                    and not any(target_signature[source_span.size :])
                )
                if exact or zero_extended_tail:
                    candidates.append(candidate)
            if len(set(candidates)) == 1:
                candidate = candidates[0]
                proposals[(section, source_boundary)] = candidate
                # The source may leave a short zero alignment tail after the
                # symbol while the target folds that tail into an expanded
                # object.  Move the following boundary with the proven edge.
                if candidate == target_span.end:
                    ordered_source = sorted(section_map)
                    boundary_index = bisect.bisect_right(
                        ordered_source, source_boundary
                    )
                    if boundary_index < len(ordered_source):
                        following = ordered_source[boundary_index]
                        following_target = section_map[following]
                        if (
                            0 < following - source_boundary <= 7
                            and target_boundary < following_target < target_span.end
                            and gap_is_zero(
                                source_dol, section, source_boundary, following
                            )
                            and not symbol_overlaps_range(
                                source_spans,
                                section,
                                source_boundary,
                                following,
                                semantic_only=True,
                            )
                        ):
                            proposals[(section, following)] = candidate

    snapped = {
        section: dict(section_map) for section, section_map in boundary_maps.items()
    }
    applied = 0
    proposal_groups: dict[tuple[str, int], dict[int, int]] = defaultdict(dict)
    for (section, source_boundary), candidate in proposals.items():
        proposal_groups[(section, candidate)][source_boundary] = candidate
    for (section, _), section_proposals in sorted(proposal_groups.items()):
        trial = dict(snapped[section])
        trial.update(section_proposals)
        ordered = [target for _, target in sorted(trial.items())]
        if any(before > after for before, after in zip(ordered, ordered[1:])):
            continue
        valid = True
        for split in source_splits:
            if split.section != section or split.start == split.end:
                continue
            target_start = trial.get(split.start)
            target_end = trial.get(split.end)
            if (
                target_start is not None
                and target_end is not None
                and target_start >= target_end
            ):
                valid = False
                break
        if valid:
            snapped[section] = trial
            applied += len(section_proposals)
    return snapped, applied


def gap_is_zero(dol: DolFile, section: str, start: int, end: int) -> bool:
    if section in {"bss", "sbss"}:
        return True
    return not any(read_dol_range(dol, start, end - start))


def symbol_overlaps_range(
    spans: dict[str, tuple[SymbolSpan, ...]],
    section: str,
    start: int,
    end: int,
    *,
    semantic_only: bool = False,
) -> bool:
    return any(
        span.start < end
        and start < span.end
        and (not semantic_only or not weak_symbol_name(span.name))
        for span in spans.get(section, ())
    )


def port_coherent_units(
    source_splits: list[SplitRange],
    source_functions: list[FunctionSymbol],
    target_functions: list[FunctionSymbol],
    boundary_maps: dict[str, dict[int, int]],
    target_symbol_spans: dict[str, tuple[list[int], list[int]]],
    target_all_symbol_spans: dict[str, tuple[list[int], list[int]]],
    source_dol: DolFile,
    target_dol: DolFile,
    source_detailed_spans: dict[str, tuple[SymbolSpan, ...]],
    target_detailed_spans: dict[str, tuple[SymbolSpan, ...]],
) -> tuple[list[PortedRange], dict[str, int], int, dict[str, tuple[str, ...]]]:
    source_by_section: dict[str, list[FunctionSymbol]] = defaultdict(list)
    target_by_section: dict[str, list[FunctionSymbol]] = defaultdict(list)
    for function in source_functions:
        source_by_section[function.section].append(function)
    for function in target_functions:
        target_by_section[function.section].append(function)

    by_unit: dict[str, list[SplitRange]] = defaultdict(list)
    for split in source_splits:
        by_unit[split.unit].append(split)

    rejected: dict[str, int] = defaultdict(int)
    rejected_units: dict[str, set[str]] = defaultdict(set)
    accepted: list[PortedRange] = []
    for unit, ranges in by_unit.items():
        candidates: list[PortedRange] = []
        reason: str | None = None
        for split in ranges:
            if split.start == split.end:
                continue
            section_map = boundary_maps.get(split.section, {})
            target_start = section_map.get(split.start)
            target_end = section_map.get(split.end)
            if target_start is None or target_end is None:
                reason = "unmapped section boundary"
                break
            if target_start >= target_end:
                reason = "invalid target range"
                break
            size_drift = split.end - split.start != target_end - target_start
            spans = (
                target_all_symbol_spans
                if size_drift or split.section in CODE_SECTIONS
                else target_symbol_spans
            )
            if boundary_crosses_symbol(
                spans, split.section, target_start
            ) or boundary_crosses_symbol(spans, split.section, target_end):
                reason = "target symbol crosses boundary"
                break
            target_split = SplitRange(
                split.unit, split.section, target_start, target_end
            )
            candidates.append(
                PortedRange(
                    source=split,
                    target_start=target_start,
                    target_end=target_end,
                    source_functions=functions_in_range(source_by_section, split),
                    target_functions=functions_in_range(
                        target_by_section, target_split
                    ),
                )
            )
        if reason is not None:
            rejected[reason] += 1
            rejected_units[reason].add(unit)
            continue
        accepted.extend(candidates)

    # Fold only short, invariant, zero-filled alignment gaps into the preceding
    # object before auditing auto-unit alignment.  This is linker padding, not
    # a standalone translation unit.
    extensions: dict[tuple[str, str, int], int] = {}
    by_section: dict[str, list[PortedRange]] = defaultdict(list)
    for item in accepted:
        by_section[item.source.section].append(item)
    for section, ranges in by_section.items():
        ranges.sort(key=lambda item: item.target_start)
        for before, after in zip(ranges, ranges[1:]):
            source_gap = after.source.start - before.source.end
            target_gap = after.target_start - before.target_end
            if not (0 < source_gap == target_gap <= 7):
                continue
            if before.target_end % 4 == 0:
                continue
            if symbol_overlaps_range(
                source_detailed_spans,
                section,
                before.source.end,
                after.source.start,
                semantic_only=True,
            ) or symbol_overlaps_range(
                target_detailed_spans,
                section,
                before.target_end,
                after.target_start,
                semantic_only=True,
            ):
                continue
            if not gap_is_zero(
                source_dol, section, before.source.end, after.source.start
            ) or not gap_is_zero(
                target_dol, section, before.target_end, after.target_start
            ):
                continue
            extensions[
                (before.source.unit, section, before.source.start)
            ] = after.target_start
    folded_padding_ranges = len(extensions)
    accepted = [
        replace(
            item,
            target_end=extensions.get(
                (item.source.unit, item.source.section, item.source.start),
                item.target_end,
            ),
        )
        for item in accepted
    ]

    # Leaving an unclaimed corridor makes decomp-toolkit synthesize an auto
    # unit.  Its endpoints must be word aligned even when the neighboring real
    # TU owns a packed byte-sized BSS tail.  Drop the adjacent projected TU in
    # that rare case so the auto corridor begins at the next safe boundary.
    while True:
        reject_units: set[str] = set()
        by_section: dict[str, list[PortedRange]] = defaultdict(list)
        for item in accepted:
            by_section[item.source.section].append(item)
        for ranges in by_section.values():
            ranges.sort(key=lambda item: item.target_start)
            for before, after in zip(ranges, ranges[1:]):
                if before.target_end >= after.target_start:
                    continue
                if before.target_end % 4:
                    reject_units.add(before.source.unit)
                if after.target_start % 4:
                    reject_units.add(after.source.unit)
        if not reject_units:
            break
        rejected["unaligned auto-unit boundary"] += len(reject_units)
        rejected_units["unaligned auto-unit boundary"].update(reject_units)
        accepted = [item for item in accepted if item.source.unit not in reject_units]

    # A single word between two claimed ranges is linker padding owned by the
    # preceding object, not a viable standalone auto unit.  Carry it with that
    # object just as decomp-toolkit does for the active EN layout.
    extensions: dict[tuple[str, str, int], int] = {}
    by_section = defaultdict(list)
    for item in accepted:
        by_section[item.source.section].append(item)
    for ranges in by_section.values():
        ranges.sort(key=lambda item: item.target_start)
        for before, after in zip(ranges, ranges[1:]):
            if after.target_start - before.target_end == 4:
                extensions[
                    (
                        before.source.unit,
                        before.source.section,
                        before.source.start,
                    )
                ] = after.target_start
    accepted = [
        replace(
            item,
            target_end=extensions.get(
                (item.source.unit, item.source.section, item.source.start),
                item.target_end,
            ),
        )
        for item in accepted
    ]

    # A coherent projection must never assign the same target bytes twice.
    previous_end: dict[str, int] = {}
    for split in sorted(
        accepted, key=lambda item: (item.source.section, item.target_start)
    ):
        if split.target_start < previous_end.get(split.source.section, 0):
            raise ValueError(
                f"Projected {split.source.unit} overlaps a prior "
                f"{split.source.section} range at 0x{split.target_start:08X}"
            )
        previous_end[split.source.section] = split.target_end
    return (
        accepted,
        dict(sorted(rejected.items())),
        folded_padding_ranges,
        {
            reason: tuple(sorted(units))
            for reason, units in sorted(rejected_units.items())
        },
    )


def build_symbol_mappings(
    ported: list[PortedRange], matches: dict[int, FunctionSymbol]
) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for split in ported:
        mappings: dict[str, str] = {}
        target_names: set[str] = set()
        source_names: set[str] = set()
        if split.source.section in CODE_SECTIONS and len(split.source_functions) == len(
            split.target_functions
        ):
            function_pairs = zip(split.source_functions, split.target_functions)
        else:
            function_pairs = (
                (source_function, target_function)
                for source_function in split.source_functions
                if (target_function := matches.get(source_function.address)) is not None
                and split.target_start <= target_function.address < split.target_end
            )
        for source_function, target_function in function_pairs:
            if (
                target_function.name in target_names
                or source_function.name in source_names
            ):
                continue
            target_names.add(target_function.name)
            source_names.add(source_function.name)
            if target_function.name != source_function.name:
                mappings[target_function.name] = source_function.name
        if mappings:
            result.setdefault(split.source.unit, {}).update(mappings)
    return dict(sorted(result.items()))


def render_splits(header: list[str], ported: list[PortedRange]) -> str:
    by_unit: dict[str, list[PortedRange]] = {}
    for split in ported:
        by_unit.setdefault(split.source.unit, []).append(split)
    lines = [*header, ""]
    for unit, ranges in by_unit.items():
        lines.append(f"{unit}:")
        for split in ranges:
            section = split.source.section
            if section not in {"extab", "extabindex"}:
                section = f".{section}"
            lines.append(
                f"\t{section:<11} "
                f"start:0x{split.target_start:08X} end:0x{split.target_end:08X}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


SYMBOL_LINE_RE = re.compile(r"^(\S+)\s+=\s+\.?([^:]+):0x([0-9A-Fa-f]+);(.*)$")
ADDRESS_SYMBOL_RE = re.compile(
    r"^(?P<prefix>@?(?:etb|eti)|lbl|fn|jumptable|gap)_[0-9A-Fa-f]{8}$"
)


def projected_symbol_name(name: str, target_address: int) -> str:
    match = ADDRESS_SYMBOL_RE.match(name)
    if match is None:
        return name
    return f"{match.group('prefix')}_{target_address:08X}"


def containing_range(
    ranges: list[PortedRange], address: int, *, target: bool
) -> PortedRange | None:
    starts = [item.target_start if target else item.source.start for item in ranges]
    index = bisect.bisect_right(starts, address) - 1
    if index < 0:
        return None
    item = ranges[index]
    end = item.target_end if target else item.source.end
    return item if address < end else None


def rewrite_symbol_line(
    line: str, *, name: str | None = None, address: int | None = None
) -> str:
    match = SYMBOL_LINE_RE.match(line)
    if match is None:
        raise ValueError(f"Unrecognized symbol line: {line}")
    result_name = name if name is not None else match.group(1)
    result_address = address if address is not None else int(match.group(3), 16)
    section_prefix = "." if " = ." in line else ""
    return (
        f"{result_name} = {section_prefix}{match.group(2)}:0x{result_address:08X};"
        f"{match.group(4)}"
    )


def render_projected_symbols(
    source_path: Path,
    target_path: Path,
    ported: list[PortedRange],
    matches: dict[int, FunctionSymbol],
) -> tuple[str, int, int, int]:
    """Project owned non-code symbols and canonical matched function names.

    Source symbols in coherently mapped non-code ranges carry the object sizes
    needed to keep split boundaries legal.  Target function boundaries remain
    authoritative; only uniquely matched functions receive their canonical EN
    names.
    """

    source_lines = source_path.read_text(encoding="utf-8").splitlines()
    target_lines = target_path.read_text(encoding="utf-8").splitlines()
    claimed_by_section: dict[str, list[PortedRange]] = defaultdict(list)
    ranges_by_section: dict[str, list[PortedRange]] = defaultdict(list)
    for item in ported:
        if item.source.section not in CODE_SECTIONS:
            claimed_by_section[item.source.section].append(item)
            if (
                item.source.end - item.source.start
                == item.target_end - item.target_start
            ):
                ranges_by_section[item.source.section].append(item)
    for ranges in [*claimed_by_section.values(), *ranges_by_section.values()]:
        ranges.sort(key=lambda item: item.source.start)
    claimed_boundaries: dict[str, list[int]] = {}
    for section, ranges in claimed_by_section.items():
        claimed_boundaries[section] = sorted(
            {
                boundary
                for item in ranges
                for boundary in (item.target_start, item.target_end)
            }
        )

    section_order: dict[str, int] = {}
    records: list[tuple[str, int, int, str]] = []
    removed = 0
    for ordinal, line in enumerate(target_lines):
        match = SYMBOL_LINE_RE.match(line)
        if match is None:
            if line.strip():
                raise ValueError(f"Unrecognized target symbol line: {line}")
            continue
        section = match.group(2)
        address = int(match.group(3), 16)
        section_order.setdefault(section, len(section_order))
        ranges = ranges_by_section.get(section, [])
        if ranges and containing_range(ranges, address, target=True) is not None:
            removed += 1
            continue
        address_name_match = ADDRESS_SYMBOL_RE.match(match.group(1))
        if (
            address_name_match is not None
            and int(match.group(1).rsplit("_", 1)[1], 16) != address
        ):
            removed += 1
            continue
        if (
            section not in CODE_SECTIONS
            and address_name_match is not None
            and containing_range(
                claimed_by_section.get(section, []), address, target=True
            )
            is None
        ):
            size_match = re.search(r"\bsize:0x([0-9A-Fa-f]+)\b", line)
            if size_match is not None:
                end = address + int(size_match.group(1), 16)
                boundaries = claimed_boundaries.get(section, [])
                index = bisect.bisect_right(boundaries, address)
                if index < len(boundaries) and boundaries[index] < end:
                    removed += 1
                    continue
        records.append((section, address, ordinal, line))

    inserted = 0
    for ordinal, line in enumerate(source_lines):
        match = SYMBOL_LINE_RE.match(line)
        if match is None:
            if line.strip():
                raise ValueError(f"Unrecognized source symbol line: {line}")
            continue
        section = match.group(2)
        address = int(match.group(3), 16)
        ranges = ranges_by_section.get(section, [])
        item = containing_range(ranges, address, target=False) if ranges else None
        if item is None:
            continue
        target_address = item.target_start + (address - item.source.start)
        target_name = projected_symbol_name(match.group(1), target_address)
        records.append(
            (
                section,
                target_address,
                ordinal,
                rewrite_symbol_line(line, name=target_name, address=target_address),
            )
        )
        inserted += 1

    desired_by_address: dict[int, str] = {}
    for split in ported:
        if split.source.section not in CODE_SECTIONS:
            continue
        if len(split.source_functions) == len(split.target_functions):
            function_pairs = zip(split.source_functions, split.target_functions)
        else:
            function_pairs = (
                (source_function, target_function)
                for source_function in split.source_functions
                if (target_function := matches.get(source_function.address)) is not None
                and split.target_start <= target_function.address < split.target_end
            )
        for source_function, target_function in function_pairs:
            desired_by_address[target_function.address] = source_function.name

    occupied: dict[str, set[int]] = defaultdict(set)
    for _, address, _, line in records:
        match = SYMBOL_LINE_RE.match(line)
        assert match is not None
        occupied[match.group(1)].add(address)

    rewritten_records: list[tuple[str, int, int, str]] = []
    renamed = 0
    conflicts = 0
    for section, address, ordinal, line in records:
        match = SYMBOL_LINE_RE.match(line)
        assert match is not None
        if section not in CODE_SECTIONS or "type:function" not in match.group(4):
            rewritten_records.append((section, address, ordinal, line))
            continue
        name = match.group(1)
        canonical = desired_by_address.get(address)
        if canonical is None:
            rewritten_records.append((section, address, ordinal, line))
            continue
        if any(owner != address for owner in occupied.get(canonical, set())):
            rewritten_records.append((section, address, ordinal, line))
            conflicts += 1
            continue
        if name != canonical:
            line = rewrite_symbol_line(line, name=canonical)
            renamed += 1
        rewritten_records.append((section, address, ordinal, line))

    rewritten_records.sort(
        key=lambda item: (
            section_order.get(item[0], len(section_order)),
            item[1],
            item[3],
        )
    )
    return (
        "\n".join(item[3] for item in rewritten_records) + "\n",
        renamed,
        conflicts,
        inserted - removed,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", help="target version under config/ and orig/")
    parser.add_argument(
        "--source", default="GSAE01", help="source version (default: GSAE01)"
    )
    parser.add_argument(
        "--write", action="store_true", help="write target splits and mappings"
    )
    parser.add_argument(
        "--write-matching",
        action="store_true",
        help="write exact source units from the target's current report",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="list rejected translation units"
    )
    args = parser.parse_args()

    source_root = Path("config") / args.source
    target_root = Path("config") / args.target
    source_dol = DolFile(Path("orig") / args.source / "sys" / "main.dol")
    target_dol = DolFile(Path("orig") / args.target / "sys" / "main.dol")
    source_functions = load_function_symbols(source_root / "symbols.txt")
    target_functions = load_function_symbols(target_root / "symbols.txt")
    target_header, _ = load_splits(target_root / "splits.txt")
    _, source_splits = load_splits(source_root / "splits.txt")

    matches = unique_function_matches(
        source_dol, source_functions, target_dol, target_functions
    )
    boundary_maps, anchor_counts = build_all_boundary_maps(
        source_splits,
        source_dol,
        target_dol,
        source_functions,
        matches,
    )
    source_symbol_spans = load_symbol_spans(source_root / "symbols.txt")
    target_symbol_spans = load_symbol_spans(target_root / "symbols.txt")
    target_named_symbol_span_index = symbol_span_index(target_symbol_spans)
    target_all_symbol_span_index = symbol_span_index(
        target_symbol_spans, include_address_symbols=True
    )
    boundary_maps, snapped_boundaries = snap_symbol_boundaries(
        source_splits,
        boundary_maps,
        source_dol,
        target_dol,
        source_symbol_spans,
        target_symbol_spans,
        target_named_symbol_span_index,
        target_all_symbol_span_index,
    )
    ported, rejected, folded_padding_ranges, rejected_units = port_coherent_units(
        source_splits,
        source_functions,
        target_functions,
        boundary_maps,
        target_named_symbol_span_index,
        target_all_symbol_span_index,
        source_dol,
        target_dol,
        source_symbol_spans,
        target_symbol_spans,
    )
    mappings = build_symbol_mappings(ported, matches)
    split_text = render_splits(target_header, ported)
    mapping_text = json.dumps(mappings, indent=2, sort_keys=True) + "\n"

    accepted_units = len({item.source.unit for item in ported})
    source_units = len({item.unit for item in source_splits})
    code_bytes = sum(
        item.target_end - item.target_start
        for item in ported
        if item.source.section in CODE_SECTIONS
    )
    data_bytes = sum(
        item.target_end - item.target_start
        for item in ported
        if item.source.section not in CODE_SECTIONS
    )
    mapped_symbols = sum(len(unit) for unit in mappings.values())
    print(
        f"{args.source} -> {args.target}: "
        f"{len(matches)} function anchors, "
        f"{accepted_units}/{source_units} coherent units, "
        f"{len(ported)}/{len(source_splits)} ranges, "
        f"0x{code_bytes:X} target code bytes, "
        f"0x{data_bytes:X} target data bytes, "
        f"{mapped_symbols} symbol mappings, "
        f"{snapped_boundaries} proven symbol-edge snaps, "
        f"{folded_padding_ranges} folded padding ranges"
    )
    for section, counts in anchor_counts.items():
        boundaries = {
            address
            for split in source_splits
            if split.section == section
            for address in (split.start, split.end)
        }
        print(
            f"  {section}: {counts[0]} direct, {counts[1]}/{len(boundaries)} mapped boundaries"
        )
    for reason, count in rejected.items():
        print(f"  skipped {count}: {reason}")
        if args.verbose:
            for unit in rejected_units.get(reason, ()):
                print(f"    {unit}")

    if args.write:
        (target_root / "splits.txt").write_text(
            split_text, encoding="utf-8", newline="\n"
        )
        (target_root / "symbol_mappings.json").write_text(
            mapping_text, encoding="utf-8", newline="\n"
        )
        canonical_symbols, renamed, conflicts, symbol_delta = render_projected_symbols(
            source_root / "symbols.txt",
            target_root / "symbols.txt",
            ported,
            matches,
        )
        (target_root / "symbols.txt").write_text(
            canonical_symbols, encoding="utf-8", newline="\n"
        )
        print(f"Wrote {target_root / 'splits.txt'}")
        print(f"Wrote {target_root / 'symbol_mappings.json'}")
        print(f"Renamed {renamed} functions in {target_root / 'symbols.txt'}")
        print(f"Projected non-code symbols (net {symbol_delta:+d} entries)")
        if conflicts:
            print(f"Preserved {conflicts} function names with canonical-name conflicts")
    if args.write_matching:
        report_path = Path("build") / args.target / "report.json"
        report = json.loads(report_path.read_text(encoding="utf-8"))
        exact_sources: set[str] = set()
        for unit in report.get("units", []):
            source_path = unit.get("metadata", {}).get("source_path")
            if not source_path:
                continue
            measures = unit.get("measures", {})
            scored = [
                measures[key]
                for key in ("fuzzy_match_percent", "matched_data_percent")
                if key in measures
            ]
            if scored and all(value == 100.0 for value in scored):
                exact_sources.add(source_path.removeprefix("src/").replace("\\", "/"))
        manifest_path = target_root / "matching_units.txt"
        manifest_path.write_text(
            "# Generated by tools/version_progress.py --write-matching\n"
            + "\n".join(sorted(exact_sources))
            + "\n",
            encoding="utf-8",
            newline="\n",
        )
        print(f"Wrote {len(exact_sources)} exact units to {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
