#!/usr/bin/env python3
"""Port high-confidence text splits and symbol mappings between retail DOLs.

The active EN v1.0 configuration remains the source of translation-unit names.
For another version, this tool matches unique normalized PowerPC function bodies,
then claims only source units whose first and last functions both match and whose
function count is unchanged. Uncertain ranges are intentionally left unassigned;
decomp-toolkit emits autogenerated units for those ranges, so progress reports
retain the full retail DOL as their denominator.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from orig.dol_xrefs import DolFile, FunctionSymbol, load_function_symbols


CODE_SECTIONS = {"init", "text"}
COUPLED_SECTIONS = {"ctors", "dtors", "extab", "extabindex"}
TOP16_MASK_OPCODES = {
    7,
    8,
    10,
    11,
    12,
    13,
    14,
    15,
    24,
    25,
    26,
    27,
    28,
    29,
    *range(32, 56),
}
TOP16_LOW2_MASK_OPCODES = {56, 57, 60, 61}
SPLIT_RANGE_RE = re.compile(
    r"^\s*(\.?\S+)\s+start:0x([0-9A-Fa-f]+)\s+end:0x([0-9A-Fa-f]+)"
)


@dataclass(frozen=True)
class SplitRange:
    unit: str
    section: str
    start: int
    end: int


@dataclass(frozen=True)
class PortedRange:
    source: SplitRange
    target_start: int
    target_end: int
    source_functions: tuple[FunctionSymbol, ...]
    target_functions: tuple[FunctionSymbol, ...]


def mask_instruction(word: int) -> int:
    opcode = word >> 26
    if opcode == 18:
        return word & 0xFC000003
    if opcode == 16:
        return word & 0xFFFF0003
    if opcode in TOP16_MASK_OPCODES:
        return word & 0xFFFF0000
    if opcode in TOP16_LOW2_MASK_OPCODES:
        return word & 0xFFFF0003
    return word


def read_dol_range(dol: DolFile, start: int, size: int) -> bytes:
    for section in dol.sections:
        if section.address <= start and start + size <= section.address + section.size:
            offset = section.offset + start - section.address
            return dol.data[offset : offset + size]
    raise ValueError(f"Range 0x{start:08X}-0x{start + size:08X} is outside {dol.path}")


def function_signature(dol: DolFile, function: FunctionSymbol) -> bytes:
    raw = read_dol_range(dol, function.address, function.size)
    if len(raw) % 4:
        raise ValueError(f"Function {function.name} has non-word size 0x{function.size:X}")
    digest = hashlib.sha1()
    for (word,) in struct.iter_unpack(">I", raw):
        digest.update(struct.pack(">I", mask_instruction(word)))
    return digest.digest()


def load_code_splits(path: Path) -> tuple[list[str], list[SplitRange], set[str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    header_end = len(lines)
    ranges: list[SplitRange] = []
    coupled_units: set[str] = set()
    unit: str | None = None
    for index, line in enumerate(lines):
        if line and not line[0].isspace() and line.endswith(":"):
            if line == "Sections:":
                continue
            if header_end == len(lines):
                header_end = index
            unit = line[:-1]
            continue
        if unit is None:
            continue
        match = SPLIT_RANGE_RE.match(line)
        if match is None:
            continue
        section = match.group(1).removeprefix(".")
        if section in COUPLED_SECTIONS:
            coupled_units.add(unit.replace("\\", "/"))
        if section not in CODE_SECTIONS:
            continue
        ranges.append(
            SplitRange(
                unit=unit.replace("\\", "/"),
                section=section,
                start=int(match.group(2), 16),
                end=int(match.group(3), 16),
            )
        )
    while header_end > 0 and not lines[header_end - 1].strip():
        header_end -= 1
    return lines[:header_end], ranges, coupled_units


def functions_in_range(
    functions_by_section: dict[str, list[FunctionSymbol]], split: SplitRange
) -> tuple[FunctionSymbol, ...]:
    return tuple(
        function
        for function in functions_by_section.get(split.section, [])
        if split.start <= function.address
        and function.address + function.size <= split.end
    )


def unique_function_matches(
    source_dol: DolFile,
    source_functions: list[FunctionSymbol],
    target_dol: DolFile,
    target_functions: list[FunctionSymbol],
) -> dict[int, FunctionSymbol]:
    source_by_signature: dict[tuple[str, bytes], list[FunctionSymbol]] = defaultdict(list)
    target_by_signature: dict[tuple[str, bytes], list[FunctionSymbol]] = defaultdict(list)
    for function in source_functions:
        if function.section in CODE_SECTIONS:
            source_by_signature[
                (function.section, function_signature(source_dol, function))
            ].append(function)
    for function in target_functions:
        if function.section in CODE_SECTIONS:
            target_by_signature[
                (function.section, function_signature(target_dol, function))
            ].append(function)

    matches: dict[int, FunctionSymbol] = {}
    for signature, candidates in source_by_signature.items():
        targets = target_by_signature.get(signature, [])
        if len(candidates) == 1 and len(targets) == 1:
            matches[candidates[0].address] = targets[0]
    return matches


def port_ranges(
    source_splits: list[SplitRange],
    coupled_units: set[str],
    source_functions: list[FunctionSymbol],
    target_functions: list[FunctionSymbol],
    matches: dict[int, FunctionSymbol],
) -> tuple[list[PortedRange], dict[str, int]]:
    source_by_section: dict[str, list[FunctionSymbol]] = defaultdict(list)
    target_by_section: dict[str, list[FunctionSymbol]] = defaultdict(list)
    for function in source_functions:
        source_by_section[function.section].append(function)
    for function in target_functions:
        target_by_section[function.section].append(function)

    rejected: dict[str, int] = defaultdict(int)
    candidates: list[PortedRange] = []
    for split in source_splits:
        if split.unit in coupled_units:
            rejected["coupled metadata"] += 1
            continue
        source_range_functions = functions_in_range(source_by_section, split)
        if not source_range_functions:
            rejected["no functions"] += 1
            continue
        first = source_range_functions[0]
        last = source_range_functions[-1]
        if first.address != split.start or last.address + last.size != split.end:
            rejected["non-function boundary"] += 1
            continue
        target_first = matches.get(first.address)
        target_last = matches.get(last.address)
        if target_first is None or target_last is None:
            rejected["unmatched edge"] += 1
            continue
        target_start = target_first.address
        target_end = target_last.address + target_last.size
        target_split = SplitRange(split.unit, split.section, target_start, target_end)
        target_range_functions = functions_in_range(target_by_section, target_split)
        if len(source_range_functions) != len(target_range_functions):
            rejected["function-count drift"] += 1
            continue
        internal_matches = [
            matches[function.address].address
            for function in source_range_functions
            if function.address in matches
        ]
        if internal_matches != sorted(internal_matches):
            rejected["non-monotonic anchors"] += 1
            continue
        candidates.append(
            PortedRange(
                source=split,
                target_start=target_start,
                target_end=target_end,
                source_functions=source_range_functions,
                target_functions=target_range_functions,
            )
        )

    accepted: list[PortedRange] = []
    previous_end: dict[str, int] = {}
    for candidate in candidates:
        section = candidate.source.section
        if candidate.target_start < previous_end.get(section, 0):
            rejected["overlapping target range"] += 1
            continue
        previous_end[section] = candidate.target_end
        accepted.append(candidate)
    return accepted, dict(sorted(rejected.items()))


def build_symbol_mappings(
    ported: list[PortedRange], matches: dict[int, FunctionSymbol]
) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for split in ported:
        mappings: dict[str, str] = {}
        target_names: set[str] = set()
        source_names: set[str] = set()
        for source_function in split.source_functions:
            target_function = matches.get(source_function.address)
            if target_function is None:
                continue
            if not (
                split.target_start
                <= target_function.address
                < split.target_end
            ):
                continue
            if target_function.name in target_names or source_function.name in source_names:
                continue
            target_names.add(target_function.name)
            source_names.add(source_function.name)
            if target_function.name != source_function.name:
                mappings[target_function.name] = source_function.name
        if mappings:
            result.setdefault(split.source.unit, {}).update(mappings)
    return dict(sorted(result.items()))


def render_splits(header: list[str], ported: list[PortedRange]) -> str:
    by_unit: dict[str, list[PortedRange]] = {}
    for split in ported:
        by_unit.setdefault(split.source.unit, []).append(split)
    lines = [*header, ""]
    for unit, ranges in by_unit.items():
        lines.append(f"{unit}:")
        for split in ranges:
            lines.append(
                f"\t.{split.source.section:<10} "
                f"start:0x{split.target_start:08X} end:0x{split.target_end:08X}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", help="target version under config/ and orig/")
    parser.add_argument("--source", default="GSAE01", help="source version (default: GSAE01)")
    parser.add_argument("--write", action="store_true", help="write target splits and mappings")
    args = parser.parse_args()

    source_root = Path("config") / args.source
    target_root = Path("config") / args.target
    source_dol = DolFile(Path("orig") / args.source / "sys" / "main.dol")
    target_dol = DolFile(Path("orig") / args.target / "sys" / "main.dol")
    source_functions = load_function_symbols(source_root / "symbols.txt")
    target_functions = load_function_symbols(target_root / "symbols.txt")
    target_header, _, _ = load_code_splits(target_root / "splits.txt")
    _, source_splits, coupled_units = load_code_splits(source_root / "splits.txt")

    matches = unique_function_matches(
        source_dol, source_functions, target_dol, target_functions
    )
    ported, rejected = port_ranges(
        source_splits, coupled_units, source_functions, target_functions, matches
    )
    mappings = build_symbol_mappings(ported, matches)
    split_text = render_splits(target_header, ported)
    mapping_text = json.dumps(mappings, indent=2, sort_keys=True) + "\n"

    code_bytes = sum(item.target_end - item.target_start for item in ported)
    mapped_symbols = sum(len(unit) for unit in mappings.values())
    print(
        f"{args.source} -> {args.target}: "
        f"{len(matches)} unique function anchors, "
        f"{len(ported)}/{len(source_splits)} code ranges, "
        f"0x{code_bytes:X} target code bytes, "
        f"{mapped_symbols} symbol mappings"
    )
    for reason, count in rejected.items():
        print(f"  skipped {count}: {reason}")

    if args.write:
        (target_root / "splits.txt").write_text(split_text, encoding="utf-8", newline="\n")
        (target_root / "symbol_mappings.json").write_text(
            mapping_text, encoding="utf-8", newline="\n"
        )
        print(f"Wrote {target_root / 'splits.txt'}")
        print(f"Wrote {target_root / 'symbol_mappings.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
